/** *****************************************************************************
 * @file    	wlan_link_handler.cpp
 * @brief   	ESP32 <-> STM32 SPI2 link: firmware update upload/download,
 *              log file listing/download/delete, SD card format and status.
 *
 *              FatFs is not thread-safe (_FS_REENTRANT is 0). This task
 *              shares the SD card with uSD_handler_task's flight-logging
 *              use via fatfs_lock()/fatfs_unlock() (fatfs_access.h).
 *
 *              See documentation/wlan_link.md for the protocol
 *              design and known issues.
 *
 * @license 	This project is released under the GNU Public License GPL-3.0

    <Larus Flight Sensor Firmware>

    This program is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with this program.  If not, see <http://www.gnu.org/licenses/>.

 **************************************************************************/

#include "system_configuration.h"
#include "main.h"
#include "FreeRTOS_wrapper.h"
#include "fatfs.h"
#include "common.h"
#include "spi.h"
#include "communicator.h"
#include "watchdog_handler.h"
#include "uSD_handler.h"
#include "fatfs_access.h"
#include "git-commit-version.h"  /* generated by a git post commit hook in /githooks. */
#include "wlan_link_protocol.h"
#include "wlan_link_handler.h"
#include <string.h>

extern SPI_HandleTypeDef hspi2;
extern DMA_HandleTypeDef hdma_spi2_rx;
extern DMA_HandleTypeDef hdma_spi2_tx;

// Idle wait for the *next* request - long gaps between web-UI activity are
// normal here.
#define WLAN_LINK_HEADER_TIMEOUT_MS   2000u

#define WLAN_LINK_MAX_PAYLOAD  (WLAN_LINK_CHUNK_SIZE + 4u) // chunk data + trailing CRC32 (incoming UPLOAD_CHUNK)

COMMON static __ALIGNED(32) uint8_t rx_payload_buffer[WLAN_LINK_MAX_PAYLOAD];
// Sized for the largest outgoing response: a DOWNLOAD_CHUNK_REQUEST DATA
// reply, which - unlike incoming UPLOAD_CHUNK - has an extra 8-byte
// wlan_link_download_chunk_response_header_t prefix before the chunk data,
// so this needs to be larger than WLAN_LINK_MAX_PAYLOAD alone would give.
#define WLAN_LINK_MAX_RESPONSE_PAYLOAD (sizeof(wlan_link_download_chunk_response_header_t) + WLAN_LINK_MAX_PAYLOAD)
COMMON static __ALIGNED(32) uint8_t tx_frame_buffer[16 + WLAN_LINK_MAX_RESPONSE_PAYLOAD];
//!< throwaway target for arm_ready_and_transmit()'s HAL_SPI_TransmitReceive_DMA()
//!< call - see that function's doc comment for why a response send can't
//!< just be transmit-only on this hardware. Content is never read.
COMMON static __ALIGNED(32) uint8_t tx_scratch_rx_buffer[sizeof(tx_frame_buffer)];

// DMA target for the incoming frame header - must be RAM, not a task-stack
// local: the WLAN-link tasks' stacks live in CCMRAM, which DMA1/DMA2
// cannot address.
COMMON static wlan_link_frame_header_t rx_header_buffer;

struct upload_state_t
{
  bool     in_progress;
  FIL      file;
  uint32_t expected_total_length; // informational only, not used to gate completeness - see handle_upload_end()
  uint32_t bytes_written;         // highest offset+length seen so far; can't detect gaps from out-of-order chunks on its own
  char     filename[WLAN_LINK_MAX_FILENAME + 1];
};
COMMON static upload_state_t upload;

// --- log file download (STM32 -> ESP32), see documentation/wlan_link.md,
// "Log file download (STM32 -> ESP32)" --------------------------------------
//
// A dedicated task (download_prefetch_runnable, below) owns the download
// FIL exclusively and keeps reading ahead into a double buffer while the
// main task (this file's wlan_link_handler_runnable) serves
// DOWNLOAD_CHUNK_REQUESTs from whichever buffer is ready and answers over
// SPI - the two overlap instead of serializing "read a chunk, then send a
// chunk". Only sequential access (chunk_index == expected_next_index) is
// supported, plus an immediate retry of the just-delivered chunk (served
// from a small cache, not the pipeline) for the case where the ESP32's own
// CRC check on a DATA response failed and it re-requests the same index -
// this project's own ESP32 client never needs anything more general than
// that.

struct download_slot_t
{
  uint32_t chunk_index;
  uint32_t valid_bytes;
  uint32_t crc32;
  uint8_t  data[WLAN_LINK_CHUNK_SIZE];
};
COMMON static download_slot_t download_slot[2];
COMMON static download_slot_t last_delivered_chunk; // cache for a cheap retry of the last chunk sent
COMMON static bool last_delivered_chunk_valid;

// "ready" = prefetch task filled this slot, main task may consume it.
// "free"  = main task is done with this slot, prefetch task may refill it.
// Reset via reset_binary_semaphore() at the top of every session
// (handle_download_begin()) since a session can start with these left in
// an arbitrary state by however the previous session ended.
COMMON static Semaphore download_slot0_ready (1, 0, (char*) "DL_S0_RDY");
COMMON static Semaphore download_slot1_ready (1, 0, (char*) "DL_S1_RDY");
COMMON static Semaphore download_slot0_free  (1, 0, (char*) "DL_S0_FREE");
COMMON static Semaphore download_slot1_free  (1, 0, (char*) "DL_S1_FREE");
// must be COMMON too (a RestrictedTask's MPU can't read ordinary
// .data/.bss); populated at runtime in wlan_link_handler_runnable().
COMMON static Semaphore *download_slot_ready[2];
COMMON static Semaphore *download_slot_free[2];
COMMON static Semaphore download_prefetch_stopped (1, 0, (char*) "DL_PF_STOP"); // signaled once the prefetch task has noticed download.active==false and stopped touching download.file

struct download_state_t
{
  bool     active;
  FIL      file;
  uint32_t file_size;
  uint32_t expected_next_index;
};
COMMON static download_state_t download;

// how long the main task waits for FatFs access - see fatfs_access.h's
// FATFS_ACCESS_WLAN_TIMEOUT_MS doc comment
#define WLAN_LINK_SD_MUTEX_TIMEOUT_MS       FATFS_ACCESS_WLAN_TIMEOUT_MS
#define WLAN_LINK_DOWNLOAD_SLOT_TIMEOUT_MS  2000u // how long the main task waits for the prefetch task per chunk

static size_t bounded_strlen (const char *s, size_t max_len)
{
  size_t n = 0;
  while ((n < max_len) && (s[n] != 0))
    ++n;
  return n;
}

//!< matches the "????*.bin" glob read_software_update() scans for
static bool filename_is_valid_bin_image (const char *name, size_t buffer_size)
{
  size_t len = bounded_strlen (name, buffer_size);
  if ((len < 8) || (len >= buffer_size)) // "????*.bin" needs at least 4+4 chars
    return false;

  const char *ext = name + len - 4;
  if (! ((ext[0] == '.')
      && ((ext[1] == 'b') || (ext[1] == 'B'))
      && ((ext[2] == 'i') || (ext[2] == 'I'))
      && ((ext[3] == 'n') || (ext[3] == 'N'))))
    return false;

  for (size_t i = 0; i < len; ++i)
    if ((name[i] == '/') || (name[i] == '\\') || (name[i] == ':'))
      return false; // no path traversal / drive prefix

  return true;
}

//!< for DELETE_REQUEST: any plain relative filename, no traversal
static bool filename_is_safe_relative (const char *name, size_t buffer_size)
{
  size_t len = bounded_strlen (name, buffer_size);
  if ((len == 0) || (len >= buffer_size))
    return false;
  if ((name[0] == '/') || (name[0] == '\\'))
    return false;
  for (size_t i = 0; i < len; ++i)
    if (name[i] == ':')
      return false;
  for (size_t i = 0; (i + 1) < len; ++i)
    if ((name[i] == '.') && (name[i + 1] == '.'))
      return false; // reject ".." anywhere

  return true;
}

//!< true if name ends in ".lrsx" (case-insensitive) - used to filter LIST_REQUEST
static bool filename_has_lrsx_extension (const char *name)
{
  size_t len = bounded_strlen (name, _MAX_LFN + 1);
  if (len < 6) // at least "x.lrsx"
    return false;
  const char *ext = name + len - 5;
  return (ext[0] == '.')
      && ((ext[1] == 'l') || (ext[1] == 'L'))
      && ((ext[2] == 'r') || (ext[2] == 'R'))
      && ((ext[3] == 's') || (ext[3] == 'S'))
      && ((ext[4] == 'x') || (ext[4] == 'X'));
}

//!< copies up to dest_size-1 bytes from src and NUL-terminates - used where
//!< a FatFs-side name (up to _MAX_LFN+1 long) needs to fit our fixed-size
//!< wire format field (WLAN_LINK_MAX_FILENAME); *.lrsx names are always
//!< short (generated as "YYMMDD_HHMMSS.lrsx", 18 chars) so this never
//!< actually truncates in practice, it's just a safety bound.
static void bounded_string_copy (char *dest, const char *src, size_t dest_size)
{
  size_t len = bounded_strlen (src, dest_size - 1);
  memcpy (dest, src, len);
  dest[len] = 0;
}

//!< every "is the SD card there" check in this file goes through this
//!< instead of reading sd_card_mounted directly - uSD_handler_task owns
//!< that flag, this is just a shared, named check.
static inline bool wlan_link_sd_card_available (void)
{
  return sd_card_mounted;
}

//!< drains any pending signal(s), then optionally raises exactly one -
//!< used to force a binary Semaphore into a known state at the start of
//!< each download session, since the *previous* session may have left it
//!< in an arbitrary state.
static void reset_binary_semaphore (Semaphore &sema, bool should_be_signaled)
{
  while (sema.wait (0))
    ; // drain
  if (should_be_signaled)
    sema.signal ();
}

//!< The actual HAL_SPI_Init() call and its Init.* fields, factored out of
//!< configure_wlan_link_gpio_and_spi() so reset_spi2_hardware() can also
//!< call this after an RCC-level SPI2 peripheral reset (see that
//!< function's doc comment) - unlike a plain disable/enable toggle, an
//!< RCC reset puts every SPI2 register back to its power-on-reset
//!< default, undoing this configuration entirely, so it must be
//!< reapplied afterward.
static void reinit_spi2_peripheral (void)
{
  hspi2.Instance = SPI2;
  hspi2.Init.Mode = SPI_MODE_SLAVE;
  hspi2.Init.Direction = SPI_DIRECTION_2LINES;
  hspi2.Init.DataSize = SPI_DATASIZE_8BIT;
  hspi2.Init.CLKPolarity = SPI_POLARITY_LOW;
  // CPHA=2EDGE (SPI MODE 1), not the more common MODE 0 - deliberately,
  // since MODE 0 requires the slave's first output bit to already be valid
  // before the master's first clock edge, with zero margin (fragile
  // without a hardware NSS pulse); MODE 1 gives a half-clock-cycle of
  // setup margin instead. Must match wlan_link_client.cpp's SPISettings()
  // mode on the ESP32 side exactly.
  hspi2.Init.CLKPhase = SPI_PHASE_2EDGE;
  hspi2.Init.NSS = SPI_NSS_SOFT; // see PB1 note above - no hardware NSS pin available here
  hspi2.Init.FirstBit = SPI_FIRSTBIT_MSB;
  hspi2.Init.TIMode = SPI_TIMODE_DISABLE;
  hspi2.Init.CRCCalculation = SPI_CRCCALCULATION_DISABLE;
  hspi2.Init.CRCPolynomial = 10;
  // In slave mode the hardware ignores BaudRatePrescaler - SCK is driven
  // externally by the ESP32 master. Set explicitly anyway so this doesn't
  // read as an oversight.
  hspi2.Init.BaudRatePrescaler = SPI_BAUDRATEPRESCALER_2;
  if (HAL_SPI_Init (&hspi2) != HAL_OK)
    Error_Handler ();
}

static void configure_wlan_link_gpio_and_spi (void)
{
  __HAL_RCC_GPIOA_CLK_ENABLE ();
  __HAL_RCC_GPIOB_CLK_ENABLE ();

  GPIO_InitTypeDef gpio = { 0 };

  // PA8: ready(high)/busy(low) output to the ESP32. Idle low until we've
  // actually finished bringing the peripheral up, below.
  HAL_GPIO_WritePin (WLAN_LINK_READY_GPIO_Port, WLAN_LINK_READY_Pin, GPIO_PIN_RESET);
  gpio.Pin = WLAN_LINK_READY_Pin;
  gpio.Mode = GPIO_MODE_OUTPUT_PP;
  gpio.Pull = GPIO_NOPULL;
  gpio.Speed = GPIO_SPEED_FREQ_VERY_HIGH;
  HAL_GPIO_Init (WLAN_LINK_READY_GPIO_Port, &gpio);

  // SCK/MISO/MOSI (PB13/14/15) and SPI2's DMA streams (DMA1_Stream3 RX /
  // DMA1_Stream4 TX) are configured automatically by HAL_SPI_MspInit()
  // when HAL_SPI_Init() (inside reinit_spi2_peripheral()) runs below -
  // explicitly re-asserted again right after, see that block's comment.
  reinit_spi2_peripheral ();

  // Explicit, redundant re-assertion of PB13/14/15 as AF5_SPI2 on top of
  // HAL_SPI_MspInit()'s own configuration (already invoked by
  // HAL_SPI_Init() above) - a no-op if MspInit already ran correctly,
  // cheap insurance against a misconfigured pin disconnecting SPI2.
  gpio.Pin = GPIO_PIN_13 | GPIO_PIN_14 | GPIO_PIN_15;
  gpio.Mode = GPIO_MODE_AF_PP;
  gpio.Pull = GPIO_NOPULL;
  gpio.Speed = GPIO_SPEED_FREQ_VERY_HIGH;
  gpio.Alternate = GPIO_AF5_SPI2;
  HAL_GPIO_Init (GPIOB, &gpio);

  // PB1: software chip-select from the ESP32, NOT SPI2's hardware NSS
  // (PB1 has no SPI2_NSS alternate function on the STM32F407 - only
  // PB9/PB12 do). The ESP32 drives it low for the duration of each SPI
  // phase and high between phases (see wlan_link_client.cpp's
  // assertChipSelect()/deassertChipSelect()); framing itself is still by
  // a fixed two-phase header-then-payload read, independent of this pin -
  // see documentation/wlan_link.md. Wired as a both-edges EXTI
  // source: wlan_link_cs_edge() (called from mti1.cpp's
  // HAL_GPIO_EXTI_Callback()) uses the assert edge to immediately drive
  // PA8/READY low, and the deassert edge to recover a link that the
  // master has genuinely stopped clocking but the STM32's own DMA never
  // noticed - see that function's doc comment.
  //
  // Deliberately configured *last*, after PA8/SPI2 above are fully up -
  // not right after the RCC clock enables like the rest of this pin's
  // config would naturally sit. HAL_GPIO_Init() with GPIO_MODE_IT_...
  // unmasks this line at the EXTI peripheral (EXTI_IMR) immediately, so
  // any edge from this point on gets latched and (once the NVIC line
  // below is enabled) dispatched to wlan_link_cs_edge() - which touches
  // SPI2/PA8. On a cold power-cycle, IO5 (the ESP32's side of this line)
  // is one of the ESP32's own SPI-boot strapping pins and can be
  // glitchy/undefined until the ESP32's firmware explicitly drives it
  // (wlan_link_client.cpp's begin(), itself called only after WiFi/AP
  // bring-up) - the STM32 boots much faster and used to have this EXTI
  // already live while SPI2/PA8 were still mid-configuration, so a glitch
  // in that window could dispatch to a half-initialized peripheral and
  // cascade into repeated reset_spi2_hardware() recovery, at
  // WLAN_LINK_PRIORITY (higher than the watchdog task) - starving it long
  // enough to trip the WWDG. Configuring this pin last still doesn't stop
  // pending edges from that window firing the moment the NVIC line below
  // is enabled, but by then SPI2/PA8 are actually ready to handle them
  // correctly instead of half-configured, which is what actually matters
  // here. See documentation/wlan_link.md and the *.RESET crash dumps this
  // was diagnosed from.
  gpio.Pin = WLAN_LINK_HANDSHAKE_Pin;
  gpio.Mode = GPIO_MODE_IT_RISING_FALLING;
  gpio.Pull = GPIO_PULLUP;
  gpio.Speed = GPIO_SPEED_FREQ_LOW;
  HAL_GPIO_Init (WLAN_LINK_HANDSHAKE_GPIO_Port, &gpio);

  // NVIC access is privileged-only on Cortex-M, and this task runs
  // unprivileged (no portPRIVILEGE_BIT) - same pattern as
  // mti1.cpp's EXTI15_10 setup / i2c1_sensors.cpp's I2C_Init().
  acquire_privileges ();
  HAL_NVIC_SetPriority (EXTI1_IRQn, WLAN_LINK_CS_ISR_PRIORITY, 0);
  HAL_NVIC_EnableIRQ (EXTI1_IRQn);
  drop_privileges ();

  HAL_GPIO_WritePin (WLAN_LINK_READY_GPIO_Port, WLAN_LINK_READY_Pin, GPIO_PIN_SET); // ready
}

static void fill_header (wlan_link_frame_header_t *header, uint8_t frame_type, uint32_t sequence_no, uint32_t payload_length)
{
  header->frame_type = frame_type;
  header->reserved0[0] = header->reserved0[1] = header->reserved0[2] = 0;
  header->sequence_no = sequence_no;
  header->payload_length = payload_length;
  header->header_crc16 = wlan_link_crc16_ccitt ((const uint8_t*) header, 12);
  header->reserved1 = 0;
}

// Signaled by wlan_link_cs_edge() every time PB1 (software chip-select) is
// released (goes high) - see recover_stuck_spi2()'s doc comment for why.
// Binary; recover_stuck_spi2() always drains any stale signal before
// waiting fresh, so a previous, unrelated release can't be mistaken for
// the one it's actually waiting for.
COMMON static Semaphore wlan_link_cs_deasserted (1, 0, (char*) "CS_DEASSERT");

// Bounds recover_stuck_spi2()'s wait for the ESP32 to release PB1. Must
// cover the longest a single phase's spi.transfer() can legitimately
// still be running - reuses WLAN_LINK_TRANSACTION_TIMEOUT_MS's value
// (see that constant, below) for the same margin reasoning; defined
// separately here only because this function comes first in the file.
#define WLAN_LINK_CS_RELEASE_TIMEOUT_MS  5000u

//!< Shared recovery step for the three arm_*() functions.
//!<
//!< HAL_SPI_Abort() (stm32f4xx_hal_spi.c) only aborts the TX/RX DMA stream
//!< it's linked to if the corresponding CR2 DMAEN bit is *currently* set at
//!< the moment it runs - `if (HAL_IS_BIT_SET(hspi->Instance->CR2,
//!< SPI_CR2_TXDMAEN)) { ... HAL_DMA_Abort(hspi->hdmatx); ... }`, same for
//!< RXDMAEN. Confirmed on real hardware: after a failed response
//!< transmission, hspi2.Instance->CR2 read back with TXDMAEN already 0 (the
//!< STM32 had since moved on to an RX-only phase), yet hdma_spi2_tx still
//!< showed HAL_DMA_STATE_BUSY with its Instance->CR EN bit set and NDTR
//!< stuck at a nonzero value - HAL_SPI_Abort() had silently skipped
//!< aborting it, since TXDMAEN was no longer set by the time it ran. A DMA
//!< stream left enabled like that can't have its configuration registers
//!< reprogrammed by any later HAL_SPI_TransmitReceive_DMA() call (locked
//!< while EN=1) - explaining reports that only a full device reset, not
//!< any software-level recovery, restored the link. Call HAL_DMA_Abort()
//!< directly and unconditionally on both streams instead of relying on
//!< HAL_SPI_Abort()'s conditional check. Toggle SPE explicitly too, so the
//!< next arm_*() call starts from a genuinely clean peripheral.
//!<
//!< Also waits (bounded, only if PB1 is still asserted right now) for the
//!< ESP32 to release it *before* touching the hardware at all. Real-
//!< hardware capture: a genuine SPI error can happen *while the ESP32
//!< master is still mid-flight* on this phase's own spi.transfer() call -
//!< a single, uninterruptible operation the master has no way to abort
//!< early, and which the slave has no way to signal "give up" into
//!< either. Resetting immediately (the original behavior here - and,
//!< because reset_spi2_hardware() can escalate to holding SPI2 in an
//!< actual RCC-level silicon reset, potentially far more disruptive than
//!< it used to be) collides with whatever the master is still clocking:
//!< the bus goes electrically dead mid-transfer (a hard SPI2 reset drives
//!< no data at all, seen on real hardware as an otherwise-inexplicable
//!< run of all-zero response bytes) instead of just failing to catch it,
//!< and re-arming a fresh receive immediately after races the remaining
//!< bytes the master is still clocking, producing a tight, self-
//!< sustaining retry storm (observed on real hardware: PA8 toggling every
//!< ~500us) for as long as the master's original transfer() call keeps
//!< running - SCK/MOSI/MISO showed genuine, continuous, correctly-clocked
//!< bus activity throughout, with PB1 asserted the whole time. Waiting
//!< for the actual release edge *before* resetting means the hardware is
//!< never touched while the master might still be mid-flight on it - the
//!< next arm_*() call only re-engages, and the reset only runs, once the
//!< master has genuinely finished.

//!< The actual hardware-reset step, factored out so reset_spi2_before_arm()
//!< (below) can reuse it unconditionally, not just on a detected error -
//!< see that function's doc comment for why.
//!<
//!< HAL_SPI_Abort()/HAL_DMA_Abort() are cooperative: each waits
//!< (bounded) for the peripheral/stream to actually confirm it stopped,
//!< and can return a non-HAL_OK status without having achieved that if
//!< the hardware doesn't cooperate in time. This code used to ignore
//!< that return value entirely - real hardware showed the link getting
//!< permanently wedged (needing a manual reset to recover) in a way that
//!< persisted even through this same reset running unconditionally
//!< before every single arm_*() call afterward, which only makes sense
//!< if the abort itself was sometimes failing silently. On that failure,
//!< force a hardware-level reset of just the SPI2 peripheral via the RCC
//!< reset/clock controller (SPI2RST in RCC_APB1RSTR) - unlike the
//!< cooperative abort, this unconditionally clears every SPI2 register
//!< back to its power-on-reset state regardless of what state its
//!< internal logic was stuck in, the same guarantee a full MCU reset
//!< gives (see documentation/wlan_link.md). Deliberately
//!< *not* extended to an RCC-level reset of the whole DMA1 controller
//!< (no per-stream reset exists on this hardware, only one shared
//!< DMA1RST bit for all 8 streams) - DMA1_Stream1/2/6 are used
//!< concurrently by GNSS_driver.cpp/D_GNSS_driver.cpp/usart_2_driver.cpp,
//!< completely unrelated to this link, and forcing a reset there would
//!< corrupt whatever transfer those happen to have in flight. Resetting
//!< SPI2 alone should still be enough in practice: once SPI2 itself is
//!< held in reset, it can generate no further DMA requests, so any
//!< stream stuck waiting on it has nothing left to wait for; a stream
//!< genuinely wedged independent of SPI2's own requests would need the
//!< wider DMA1 reset instead, not yet attempted here.
//!<
//!< Escalation criterion, tried and reverted: gating the RCC-level reset on
//!< HAL_DMA_Abort()'s return value (checked only when hdma->State was
//!< actually HAL_DMA_STATE_BUSY, to filter out the routine HAL_ERROR /
//!< HAL_DMA_ERROR_NO_XFER case where there was nothing to abort) looked
//!< correct, but made real-hardware behavior markedly *worse*: with the
//!< hard reset now rarely firing, the "stuck shift register" corruption
//!< (long runs of one repeated byte - e.g. 0x91 - identical across several
//!< consecutive, otherwise-unrelated transactions) came back essentially
//!< unthrottled, something the frequently-firing hard reset had evidently
//!< been clearing away as a side effect even while triggering on the
//!< "wrong" (falsely-positive) signal. In other words: whatever causes
//!< that corruption lives in SPI2's own internal shift/data register
//!< state, which HAL_DMA_Abort()'s return value and hdma->State never
//!< observe either way - "the DMA handle thinks nothing needs aborting"
//!< and "SPI2 is still holding stale, stuck data" are independent facts,
//!< so no return-value-based criterion built on the DMA handles can ever
//!< gate this correctly. Conclusion: don't gate it at all. Run the
//!< RCC-level SPI2 reset unconditionally, every single call - matching
//!< what this file's user originally suggested early in this
//!< investigation (reset the SPI/DMA hardware after every transfer,
//!< unconditionally). The cooperative aborts are still attempted first,
//!< best-effort, so any DMA stream still actually mid-transfer at least
//!< gets a chance to wind down cleanly before SPI2 is yanked into silicon
//!< reset out from under it - but neither their success nor failure gates
//!< the reset that follows.
static void reset_spi2_hardware (void)
{
  HAL_SPI_Abort (&hspi2);
  if (hdma_spi2_tx.State == HAL_DMA_STATE_BUSY)
    HAL_DMA_Abort (&hdma_spi2_tx);
  if (hdma_spi2_rx.State == HAL_DMA_STATE_BUSY)
    HAL_DMA_Abort (&hdma_spi2_rx);

  __HAL_RCC_SPI2_FORCE_RESET ();
  __HAL_RCC_SPI2_RELEASE_RESET ();
  reinit_spi2_peripheral ();
}

//!< Shared by recover_stuck_spi2() and reset_spi2_before_arm(): blocks
//!< (bounded, WLAN_LINK_CS_RELEASE_TIMEOUT_MS) until the ESP32 has
//!< genuinely released PB1 (CS), or returns immediately if it already has
//!< - see reset_spi2_hardware()'s doc comment for why touching SPI2 any
//!< earlier can corrupt bytes the master might still be mid-flight on.
//!< Drain first, then check the pin level - not the other way round: if
//!< the drain happened after the pin check instead, a release edge
//!< landing in between the two would have its signal eaten by the drain,
//!< and the wait() below would then block for the full timeout despite
//!< PB1 already being high.
static void wait_for_cs_release (void)
{
  while (wlan_link_cs_deasserted.wait (0))
    ; // drain any stale signal from an earlier, unrelated release
  if (HAL_GPIO_ReadPin (WLAN_LINK_HANDSHAKE_GPIO_Port, WLAN_LINK_HANDSHAKE_Pin) != GPIO_PIN_SET)
    wlan_link_cs_deasserted.wait (pdMS_TO_TICKS (WLAN_LINK_CS_RELEASE_TIMEOUT_MS));
}

static void recover_stuck_spi2 (void)
{
  wait_for_cs_release ();
  reset_spi2_hardware ();
}

// PB1 software chip-select, see documentation/wlan_link.md ("Framing
// without a hardware NSS pin") for the full mechanism and what case 1/2
// below detect. Notes not obvious from the doc alone:
//
// - Assert edge also drives READY low here (not just in the arm_*()
//   functions' task context) so "READY is low whenever CS is asserted"
//   is a hardware-immediate guarantee, independent of task scheduling -
//   matters most right after reset/boot before this task has run at all.
// - Case 1's flag clear is deliberately the only thing done directly from
//   this ISR (no HAL_SPI_Abort()/SPE toggle) to avoid disturbing the
//   nested ISR's own state further; any resulting garbled header is
//   still caught by the main loop's header_crc16 check.
// - Case 2 can't call recover_stuck_spi2() directly from here either
//   (HAL_SPI_Abort() has its own HAL_GetTick()-based wait, vulnerable to
//   the same priority-inversion class of bug as case 1's condition) - it
//   hands off to task context via the same WLAN_LINK_SPI2_NOTIFY_ERROR
//   path HAL_SPI_ErrorCallback() (spi.cpp) uses for hardware errors.
// - Case 2 checks NVIC_GetPendingIRQ(), not just NVIC_GetActive(): without
//   it, a DMA-complete interrupt merely queued (genuinely finished, just
//   not yet serviced because this higher-priority handler preempted it)
//   would look identical to "genuinely short" and trigger a false
//   recovery on an otherwise-successful transfer.
void wlan_link_cs_edge (void)
{
  if (HAL_GPIO_ReadPin (WLAN_LINK_HANDSHAKE_GPIO_Port, WLAN_LINK_HANDSHAKE_Pin) != GPIO_PIN_SET)
    {
      // assert edge (CS just went low) - see the doc comment above
      HAL_GPIO_WritePin (WLAN_LINK_READY_GPIO_Port, WLAN_LINK_READY_Pin, GPIO_PIN_RESET);
      return;
    }

  // Unconditional on every release, regardless of what follows below -
  // recover_stuck_spi2() (task context, possibly waiting right now) needs
  // to know the master has genuinely stopped clocking, independent of
  // whether this particular release also happens to need case 1/2 below.
  wlan_link_cs_deasserted.signal_from_ISR ();

  if (NVIC_GetActive (DMA1_Stream3_IRQn))
    {
      __HAL_SPI_CLEAR_OVRFLAG (&hspi2);
      __HAL_SPI_CLEAR_FREFLAG (&hspi2);
      return;
    }

  // DMA1_Stream3_IRQn's active check already ruled out above (would have
  // returned) - only its *pending* state still needs checking here.
  if ((hspi2.State != HAL_SPI_STATE_READY)
      && ! NVIC_GetPendingIRQ (DMA1_Stream3_IRQn)
      && ! NVIC_GetActive (DMA1_Stream4_IRQn) && ! NVIC_GetPendingIRQ (DMA1_Stream4_IRQn))
    {
      notify_SPI2_task_from_ISR (WLAN_LINK_SPI2_NOTIFY_ERROR);
    }
}

/**
 * @brief EXTI1 interrupt handler (PB1, ESP32 software chip-select)
 */
extern "C" void EXTI1_IRQHandler (void)
{
  HAL_GPIO_EXTI_IRQHandler (WLAN_LINK_HANDSHAKE_Pin);
}

//!< Arms the SPI2 TX DMA transfer *before* raising PA8 (ready), so the DMA
//!< is always loaded before the ESP32 can possibly see PA8 high, no matter
//!< how fast it reacts. Uses HAL_SPI_TransmitReceive_DMA(), not a
//!< transmit-only call: SPI2 is 2-line full-duplex, so the ESP32 drives
//!< MOSI the whole time it's clocking our response out on MISO regardless
//!< of what this side "intends" - a transmit-only DMA call leaves those
//!< incoming bytes unserviced, which real hardware showed reliably wedging
//!< the peripheral on large (4kB+) responses. Recovers via
//!< recover_stuck_spi2() and returns false on a stall instead of
//!< asserting - the master's own exchangeWithRetry() already retries on
//!< any transport failure, so this side just needs to get back to idle.
//!< See documentation/wlan_link.md.
// Must stay comfortably above the ESP32's own WLAN_LINK_READY_TIMEOUT_MS
// (3000ms, wlan_link_client.h), which only bounds how long the ESP32
// waits to *notice* PA8 going high, not how long it then takes to start
// clocking the response.
#define WLAN_LINK_TRANSACTION_TIMEOUT_MS  5000u

//!< Unconditional per-arm hardware reset (see reset_spi2_hardware()) -
//!< HAL-level diagnostics found nothing explaining earlier wire-level
//!< corruption, and the official errata sheet (ES0182) lists no
//!< SPI-specific silicon bug either, so this runs the reset on *every*
//!< arm instead of only on a detected error. Also waits for CS release
//!< first (wait_for_cs_release()) - can take up to ~2ms in the rare case,
//!< long enough for the ESP32's own tight poll loop to reassert CS for
//!< the next phase before the reset finishes otherwise. See
//!< documentation/wlan_link.md.
static void reset_spi2_before_arm (void)
{
  wait_for_cs_release ();
  reset_spi2_hardware ();
}

static bool arm_ready_and_transmit (uint8_t *data, uint16_t len)
{
  register_SPI_usertask (&hspi2);
  ASSERT (len <= sizeof(tx_scratch_rx_buffer));
  reset_spi2_before_arm ();
  HAL_StatusTypeDef status = HAL_SPI_TransmitReceive_DMA (&hspi2, data, tx_scratch_rx_buffer, len);
  if (HAL_OK != status)
    {
      // Arming can fail if the peripheral is still recovering from an
      // earlier error - recoverable like a timeout, not fatal.
      recover_stuck_spi2 ();
      return false;
    }

  HAL_GPIO_WritePin (WLAN_LINK_READY_GPIO_Port, WLAN_LINK_READY_Pin, GPIO_PIN_SET);

  // Loops on WLAN_LINK_SPI2_NOTIFY_HALF_COMPLETE like the other two arm_*()
  // functions, and treats WLAN_LINK_SPI2_NOTIFY_ERROR (spi.h, from
  // HAL_SPI_ErrorCallback()) as a failure rather than success.
  uint32_t notification_value;
  for (;;)
    {
      BaseType_t result = xTaskNotifyWait (0xffffffff, 0, &notification_value, pdMS_TO_TICKS (WLAN_LINK_TRANSACTION_TIMEOUT_MS));
      if (result != pdTRUE || notification_value == WLAN_LINK_SPI2_NOTIFY_ERROR)
        {
          recover_stuck_spi2 ();
          return false;
        }
      if (notification_value == WLAN_LINK_SPI2_NOTIFY_FULL_COMPLETE)
        break;
    }

  return true;
}

//!< Mirrors arm_ready_and_transmit(): arms the SPI2 RX DMA transfer *before*
//!< raising PA8, so the ESP32 (which waits for this signal before clocking
//!< a request's payload) can never start sending before the DMA is armed
//!< to catch it. Unlike the TX side, this one's return value is NOT safe
//!< to ignore: on false, 'data' is undefined/incomplete - the caller must
//!< skip dispatching and go back to waiting for a fresh header.
static bool arm_ready_and_receive (uint8_t *data, uint16_t len)
{
  register_SPI_usertask (&hspi2);
  reset_spi2_before_arm ();
  HAL_StatusTypeDef status = HAL_SPI_Receive_DMA (&hspi2, data, len);
  if (HAL_OK != status)
    {
      // Peripheral may still be recovering from an earlier error - see
      // arm_ready_and_transmit()'s doc comment.
      recover_stuck_spi2 ();
      return false;
    }

  HAL_GPIO_WritePin (WLAN_LINK_READY_GPIO_Port, WLAN_LINK_READY_Pin, GPIO_PIN_SET);

  uint32_t notification_value;
  for (;;)
    {
      BaseType_t result = xTaskNotifyWait (0xffffffff, 0, &notification_value, pdMS_TO_TICKS (WLAN_LINK_TRANSACTION_TIMEOUT_MS));
      // WLAN_LINK_SPI2_NOTIFY_ERROR (spi.h) - from HAL_SPI_ErrorCallback() -
      // is a failure here too, not just an xTaskNotifyWait() timeout; see
      // arm_ready_and_transmit()'s doc comment.
      if (result != pdTRUE || notification_value == WLAN_LINK_SPI2_NOTIFY_ERROR)
        {
          recover_stuck_spi2 ();
          return false;
        }
      if (notification_value == WLAN_LINK_SPI2_NOTIFY_FULL_COMPLETE)
        return true;
    }
}

//!< Arms the SPI2 RX DMA for the *next incoming request header*, then
//!< raises PA8 - mirroring arm_ready_and_receive()/arm_ready_and_transmit():
//!< the master must never be able to see "ready" before the DMA is
//!< actually armed to catch it. Returns true once a full header was
//!< received within timeout_ms; false on timeout/error (recovered via
//!< recover_stuck_spi2()) - *header is then undefined/stale, callers
//!< already only trust it after a true return.
static bool arm_ready_for_header (wlan_link_frame_header_t *header, uint32_t timeout_ms)
{
  HAL_GPIO_WritePin (WLAN_LINK_READY_GPIO_Port, WLAN_LINK_READY_Pin, GPIO_PIN_RESET);

  // SPI2 is full-duplex: the ESP32 keeps driving MOSI while clocking out a
  // response too, so a preceding transmit-only phase can leave an
  // unserviced overrun (SPI_FLAG_OVR) that would otherwise corrupt the
  // first byte of this fresh reception. Clear defensively on every arm.
  __HAL_SPI_CLEAR_OVRFLAG (&hspi2);
  __HAL_SPI_CLEAR_FREFLAG (&hspi2);

  register_SPI_usertask (&hspi2);
  reset_spi2_before_arm ();
  HAL_StatusTypeDef status = HAL_SPI_Receive_DMA (&hspi2, (uint8_t*) header, sizeof(*header));
  if (HAL_OK != status)
    {
      recover_stuck_spi2 ();
      return false;
    }

  HAL_GPIO_WritePin (WLAN_LINK_READY_GPIO_Port, WLAN_LINK_READY_Pin, GPIO_PIN_SET);

  uint32_t notification_value;
  for (;;)
    {
      BaseType_t result = xTaskNotifyWait (0xffffffff, 0, &notification_value, pdMS_TO_TICKS (timeout_ms));
      // WLAN_LINK_SPI2_NOTIFY_ERROR (spi.h) - from HAL_SPI_ErrorCallback() -
      // is a failure here too, not just an xTaskNotifyWait() timeout; see
      // arm_ready_and_transmit()'s doc comment.
      if (result != pdTRUE || notification_value == WLAN_LINK_SPI2_NOTIFY_ERROR)
        {
          recover_stuck_spi2 ();
          return false;
        }
      if (notification_value == WLAN_LINK_SPI2_NOTIFY_FULL_COMPLETE)
        return true;
    }
}

//!< builds a frame in tx_frame_buffer and sends it via arm_ready_and_transmit().
//!< Every frame gets a trailing CRC32 over its payload (word-padded like
//!< UPLOAD_CHUNK's own trailer) - header_crc16 only covers the 12-byte
//!< header, never the payload. payload_length in the header still reports
//!< only the payload's own size, not this trailer.
static void send_frame (uint8_t frame_type, uint32_t sequence_no, const void *payload, uint16_t payload_len)
{
  ASSERT (16u + payload_len + 4u <= sizeof(tx_frame_buffer));

  wlan_link_frame_header_t header;
  fill_header (&header, frame_type, sequence_no, payload_len);

  memcpy (tx_frame_buffer, &header, sizeof(header));
  if (payload_len > 0)
    memcpy (tx_frame_buffer + sizeof(header), payload, payload_len);

  uint32_t word_aligned_len = payload_len & ~3u;
  uint32_t crc = wlan_link_crc32_update (wlan_link_crc32_init (), tx_frame_buffer + sizeof(header), word_aligned_len);
  if (word_aligned_len != payload_len)
    {
      uint8_t padded[4] = { 0, 0, 0, 0 };
      memcpy (padded, tx_frame_buffer + sizeof(header) + word_aligned_len, payload_len - word_aligned_len);
      crc = wlan_link_crc32_update (crc, padded, 4);
    }
  memcpy (tx_frame_buffer + sizeof(header) + payload_len, &crc, sizeof(crc));

  arm_ready_and_transmit (tx_frame_buffer, (uint16_t) (sizeof(header) + payload_len + 4u));
}

static void send_ack (uint32_t sequence_no)
{
  wlan_link_ack_payload_t payload;
  payload.sequence_no = sequence_no;
  send_frame (WLAN_FRAME_ACK, sequence_no, &payload, sizeof(payload));
}

static void send_nack (uint32_t sequence_no, wlan_link_nack_reason_t reason)
{
  wlan_link_nack_payload_t payload;
  payload.sequence_no = sequence_no;
  payload.reason = (uint8_t) reason;
  send_frame (WLAN_FRAME_NACK, sequence_no, &payload, sizeof(payload));
}

//!< closes and removes a partially-received upload, e.g. after ABORT or a
//!< failed CRC check - never leave a half-written *.bin behind
static void discard_upload (void)
{
  if (upload.in_progress)
    {
      f_close (&upload.file);
      f_unlink (upload.filename);
      fatfs_unlock (); // acquired for the whole session in handle_upload_begin()
    }
  upload.in_progress = false;
}

static void handle_upload_begin (const wlan_link_frame_header_t &header, const uint8_t *payload)
{
  if (logging_active)
    {
      send_nack (header.sequence_no, WLAN_NACK_LOGGING_ACTIVE);
      return;
    }
  if (! wlan_link_sd_card_available ())
    {
      send_nack (header.sequence_no, WLAN_NACK_NO_SD_CARD);
      return;
    }

  const wlan_link_upload_begin_payload_t *request = (const wlan_link_upload_begin_payload_t*) payload;

  if (! filename_is_valid_bin_image (request->filename, sizeof(request->filename)))
    {
      send_nack (header.sequence_no, WLAN_NACK_BAD_FILENAME);
      return;
    }

  if (upload.in_progress) // a previous upload wasn't cleanly finished - abandon it (also releases its lock)
    discard_upload ();

  // held for the whole upload session (through UPLOAD_CHUNK/_END/_ABORT),
  // released in discard_upload() or at the end of handle_upload_end().
  if (! fatfs_lock (pdMS_TO_TICKS (WLAN_LINK_SD_MUTEX_TIMEOUT_MS)))
    {
      send_nack (header.sequence_no, WLAN_NACK_SD_CARD_BUSY);
      return;
    }

  memcpy (upload.filename, request->filename, sizeof(request->filename));
  upload.filename[WLAN_LINK_MAX_FILENAME] = 0; // guarantee NUL-termination

  // FA_READ is needed too: handle_upload_end() reads the file back to
  // verify the whole-file CRC32 before committing to a reboot.
  FRESULT result = f_open (&upload.file, upload.filename, FA_CREATE_ALWAYS | FA_WRITE | FA_READ);
  if (result != FR_OK)
    {
      fatfs_unlock ();
      send_nack (header.sequence_no, WLAN_NACK_INTERNAL_ERROR);
      return;
    }

  upload.in_progress = true;
  upload.expected_total_length = request->total_length;
  upload.bytes_written = 0;

  send_ack (header.sequence_no);
}

static void handle_upload_chunk (const wlan_link_frame_header_t &header, const uint8_t *payload)
{
  if (! upload.in_progress)
    {
      send_nack (header.sequence_no, WLAN_NACK_OUT_OF_SEQUENCE);
      return;
    }

  uint32_t data_len = header.payload_length; // trailing 4B CRC32 already excluded by caller
  const uint32_t *trailer = (const uint32_t*) (payload + data_len);

  // data_len is not necessarily a multiple of 4 for the very last chunk of a
  // file (though in practice it always will be for pack.py-built images,
  // since their total length is already word-aligned by construction) - pad
  // with zero bytes up to the next word boundary before CRC'ing, matching
  // how pack.py's ReadApp.get_binary() word-aligns the image. The ESP32
  // side MUST compute the per-chunk CRC32 the same way for this to match.
  uint32_t word_aligned_len = data_len & ~3u;
  uint32_t remainder = data_len - word_aligned_len;

  uint32_t received_crc32 = wlan_link_crc32_update (wlan_link_crc32_init (), payload, word_aligned_len);
  if (remainder != 0)
    {
      uint8_t padded[4] = { 0, 0, 0, 0 };
      memcpy (padded, payload + word_aligned_len, remainder);
      received_crc32 = wlan_link_crc32_update (received_crc32, padded, 4);
    }

  if (received_crc32 != *trailer)
    {
      send_nack (header.sequence_no, WLAN_NACK_PAYLOAD_CRC);
      return;
    }

  // chunks are idempotent: seek to the position implied by the sequence
  // number rather than trusting "current file position", so a resent chunk
  // can't corrupt the file (see documentation, "Sequencing and reliability")
  FSIZE_t offset = (FSIZE_t) header.sequence_no * WLAN_LINK_CHUNK_SIZE;
  if (f_lseek (&upload.file, offset) != FR_OK)
    {
      send_nack (header.sequence_no, WLAN_NACK_INTERNAL_ERROR);
      return;
    }

  UINT written = 0;
  FRESULT result = f_write (&upload.file, payload, data_len, &written);
  if ((result != FR_OK) || (written != data_len))
    {
      send_nack (header.sequence_no, WLAN_NACK_INTERNAL_ERROR);
      return;
    }

  if (offset + data_len > upload.bytes_written)
    upload.bytes_written = (uint32_t) (offset + data_len);

  send_ack (header.sequence_no);
}

static void handle_upload_end (const wlan_link_frame_header_t &header, const uint8_t *payload)
{
  if (! upload.in_progress)
    {
      send_nack (header.sequence_no, WLAN_NACK_OUT_OF_SEQUENCE);
      return;
    }

  const wlan_link_upload_end_payload_t *request = (const wlan_link_upload_end_payload_t*) payload;
  // Copy the expected CRC out *now*, before rx_payload_buffer (== payload,
  // request points into it) gets reused below as the whole-file re-read
  // scratch buffer - reading request->whole_file_crc32 after the read loop
  // would compare against the last-read file chunk's first 4 bytes instead.
  uint32_t expected_crc32 = request->whole_file_crc32;

  // Re-derive the whole-file CRC32 from what was actually written rather
  // than trusting a value accumulated chunk-by-chunk in RAM, since chunks
  // may have arrived out of order or been resent. Also covers completeness:
  // a gap left by a never-(re)sent chunk leaves stale bytes that won't
  // match either (FatFs doesn't zero-fill past the previous EOF).
  FRESULT result = f_lseek (&upload.file, 0);
  uint32_t crc = wlan_link_crc32_init ();
  if (result == FR_OK)
    {
      for (;;)
	{
	  UINT bytes_read = 0;
	  result = f_read (&upload.file, rx_payload_buffer, WLAN_LINK_CHUNK_SIZE, &bytes_read);
	  if ((result != FR_OK) || (bytes_read == 0))
	    break;
	  uint32_t word_aligned = bytes_read & ~3u;
	  crc = wlan_link_crc32_update (crc, rx_payload_buffer, word_aligned);
	  if (word_aligned != bytes_read)
	    {
	      uint8_t padded[4] = { 0, 0, 0, 0 };
	      memcpy (padded, rx_payload_buffer + word_aligned, bytes_read - word_aligned);
	      crc = wlan_link_crc32_update (crc, padded, 4);
	    }
	  if (bytes_read < WLAN_LINK_CHUNK_SIZE)
	    break;
	}
    }

  if (crc != expected_crc32)
    {
      send_nack (header.sequence_no, WLAN_NACK_PAYLOAD_CRC);
      discard_upload ();
      return;
    }

  if (logging_active) // re-check right before committing to a reboot - see "Logging pause"
    {
      send_nack (header.sequence_no, WLAN_NACK_LOGGING_ACTIVE);
      discard_upload ();
      return;
    }

  f_close (&upload.file);
  // Unmount while still holding the lock, not after releasing it (as this
  // used to) - releasing first left a window where another task could
  // acquire the lock and touch the same shared FATFS/SDIO hardware
  // concurrently with this unmount. That window got much easier to hit
  // once uSD_handler_task started polling the card-detect pin every
  // 100ms while grounded (see uSD_handler.cpp's SD-card-removal
  // detection) - each poll is a fresh chance to acquire the lock right
  // here. delay(100) first: give the SD card a moment to flush, mirrors
  // uSD_helpers.cpp:620-622.
  delay (100);
  f_mount (0, "", 0);
  upload.in_progress = false;
  fatfs_unlock (); // acquired for the whole session in handle_upload_begin()

  send_ack (header.sequence_no);

  delay (100);

  // let the watchdog reset the system - the same idiom already used for
  // SD-card-reinsertion (watchdog_handler.cpp) and crash dumps
  // (uSD_helpers.cpp::write_crash_dump()); read_software_update() picks the
  // new file up unconditionally early on the next boot.
  user_initiated_reset = true;
  while (true)
    ; // wake watchdog
}

static void handle_upload_abort (const wlan_link_frame_header_t &header)
{
  discard_upload ();
  send_ack (header.sequence_no);
}

//!< stops the download prefetch task and releases the session's SD lock -
//!< safe to call whether or not a session is actually active
static void end_download_session (void)
{
  if (download.active)
    {
      download.active = false;
      download_prefetch_stopped.wait (); // block until the prefetch task confirms it stopped touching download.file
      f_close (&download.file);
      fatfs_unlock ();
    }
}

// Cache for handle_list_request()'s real (non-stub) path: an open DIR
// positioned so the next f_readdir() call returns the entry right after
// list_dir_cache_next_index - 1, reused when a request continues
// sequentially from the previous one (the only access pattern any real
// client uses, see handleFilesList()/downloadAllFiles(), web_server.cpp)
// instead of re-scanning the directory from the start every single time.
// Safe to keep open across separate requests (each its own
// fatfs_lock()/fatfs_unlock() cycle, not held for the whole listing):
// uSD_handler_task, the only other task that ever writes into logger/,
// only does so while airborne, and holds the FatFs lock for the entire
// flight while it does - so any window where handle_list_request() can
// acquire that lock at all is already a window where nothing else is
// concurrently changing this directory. The only other writer is this
// same task's own handle_delete_request()/handle_format_request(),
// invalidated explicitly below.
COMMON static DIR list_dir_cache;
COMMON static uint32_t list_dir_cache_next_index;
COMMON static bool list_dir_cache_open = false;

static void invalidate_list_dir_cache (void)
{
  if (list_dir_cache_open)
    {
      f_closedir (&list_dir_cache);
      list_dir_cache_open = false;
    }
}

static void handle_list_request (const wlan_link_frame_header_t &header, const uint8_t *payload)
{
  if (! wlan_link_sd_card_available ())
    {
      send_nack (header.sequence_no, WLAN_NACK_NO_SD_CARD);
      return;
    }

  const wlan_link_list_request_payload_t *request = (const wlan_link_list_request_payload_t*) payload;

  if (! fatfs_lock (pdMS_TO_TICKS (WLAN_LINK_SD_MUTEX_TIMEOUT_MS)))
    {
      send_nack (header.sequence_no, WLAN_NACK_SD_CARD_BUSY);
      return;
    }

  wlan_link_list_response_payload_t response;
  memset (&response, 0, sizeof(response));

  bool resuming = list_dir_cache_open && (request->entry_index == list_dir_cache_next_index);
  if (! resuming)
    {
      invalidate_list_dir_cache ();
      list_dir_cache_open = (f_opendir (&list_dir_cache, "logger") == FR_OK);
    }

  if (list_dir_cache_open)
    {
      // 0 when resuming - the next matching entry f_readdir() returns
      // *is* the requested one; otherwise skip that many matches first,
      // same as a full rescan from the start would.
      uint32_t remaining_to_skip = resuming ? 0 : request->entry_index;
      FILINFO filinfo;
      for (;;)
	{
	  FRESULT result = f_readdir (&list_dir_cache, &filinfo);
	  if ((result != FR_OK) || (filinfo.fname[0] == 0))
	    {
	      invalidate_list_dir_cache (); // end of directory (or an error) - nothing left to resume from
	      break;
	    }
	  if ((filinfo.fattrib & AM_DIR) != 0)
	    continue;
	  if (! filename_has_lrsx_extension (filinfo.fname))
	    continue;

	  if (remaining_to_skip > 0)
	    {
	      --remaining_to_skip;
	      continue;
	    }

	  response.has_entry = 1;
	  response.file_size = (uint32_t) filinfo.fsize;
	  response.fat_date = filinfo.fdate;
	  response.fat_time = filinfo.ftime;
	  bounded_string_copy (response.filename, filinfo.fname, sizeof(response.filename));
	  list_dir_cache_next_index = request->entry_index + 1; // ready for the next sequential request
	  break;
	}
    }

  fatfs_unlock ();

  send_frame (WLAN_FRAME_DATA, header.sequence_no, &response, sizeof(response));
}

static void handle_download_begin (const wlan_link_frame_header_t &header, const uint8_t *payload)
{
  if (logging_active) // reading an old file still touches the same non-reentrant FatFs volume - see "Logging pause"
    {
      send_nack (header.sequence_no, WLAN_NACK_LOGGING_ACTIVE);
      return;
    }
  if (! wlan_link_sd_card_available ())
    {
      send_nack (header.sequence_no, WLAN_NACK_NO_SD_CARD);
      return;
    }

  const wlan_link_download_begin_payload_t *request = (const wlan_link_download_begin_payload_t*) payload;
  if (! filename_is_safe_relative (request->filename, sizeof(request->filename)))
    {
      send_nack (header.sequence_no, WLAN_NACK_BAD_FILENAME);
      return;
    }

  if (download.active) // a previous session wasn't cleanly ended - abandon it (also releases its lock)
    end_download_session ();

  // held for the whole download session (through DOWNLOAD_CHUNK_REQUEST/
  // _END), released in end_download_session() - same reasoning as the
  // upload session lock, see handle_upload_begin().
  if (! fatfs_lock (pdMS_TO_TICKS (WLAN_LINK_SD_MUTEX_TIMEOUT_MS)))
    {
      send_nack (header.sequence_no, WLAN_NACK_SD_CARD_BUSY);
      return;
    }

  char path[8 + WLAN_LINK_MAX_FILENAME + 1] = "logger/";
  size_t prefix_len = bounded_strlen (path, sizeof(path));
  size_t name_len = bounded_strlen (request->filename, sizeof(request->filename));
  memcpy (path + prefix_len, request->filename, name_len);
  path[prefix_len + name_len] = 0;

  FRESULT result = f_open (&download.file, path, FA_READ);
  if (result != FR_OK)
    {
      fatfs_unlock ();
      send_nack (header.sequence_no, (result == FR_NO_FILE) ? WLAN_NACK_FILE_NOT_FOUND : WLAN_NACK_INTERNAL_ERROR);
      return;
    }

  download.file_size = (uint32_t) f_size (&download.file);
  download.expected_next_index = 0;
  last_delivered_chunk_valid = false;

  // force a known starting state regardless of how the last session ended
  reset_binary_semaphore (download_slot0_ready, false);
  reset_binary_semaphore (download_slot1_ready, false);
  reset_binary_semaphore (download_slot0_free, true);
  reset_binary_semaphore (download_slot1_free, true);
  reset_binary_semaphore (download_prefetch_stopped, false);

  download.active = true; // download_prefetch_runnable() picks this up and starts reading ahead

  wlan_link_download_begin_response_payload_t response;
  response.file_size = download.file_size;
  send_frame (WLAN_FRAME_DATA, header.sequence_no, &response, sizeof(response));
}

//!< builds and transmits a DOWNLOAD_CHUNK_REQUEST DATA response straight
//!< from a filled download_slot_t - shared by the normal path and the
//!< cached-retry path
static void send_download_chunk_response (uint32_t request_sequence_no, const download_slot_t &slot)
{
  wlan_link_download_chunk_response_header_t resp_header;
  resp_header.chunk_index = slot.chunk_index;
  resp_header.valid_bytes = slot.valid_bytes;

  uint32_t offset = 16 + sizeof(resp_header);
  memcpy (tx_frame_buffer + 16, &resp_header, sizeof(resp_header));
  memcpy (tx_frame_buffer + offset, slot.data, slot.valid_bytes);

  uint32_t *trailer = (uint32_t*) (tx_frame_buffer + offset + slot.valid_bytes);
  *trailer = slot.crc32;

  wlan_link_frame_header_t header;
  fill_header (&header, WLAN_FRAME_DATA, request_sequence_no, (uint32_t) (sizeof(resp_header) + slot.valid_bytes));
  memcpy (tx_frame_buffer, &header, sizeof(header));

  arm_ready_and_transmit (tx_frame_buffer, (uint16_t) (offset + slot.valid_bytes + 4));
}

static void handle_download_chunk_request (const wlan_link_frame_header_t &header, const uint8_t *payload)
{
  if (! download.active)
    {
      send_nack (header.sequence_no, WLAN_NACK_OUT_OF_SEQUENCE);
      return;
    }

  const wlan_link_download_chunk_request_payload_t *request = (const wlan_link_download_chunk_request_payload_t*) payload;
  uint32_t requested = request->chunk_index;

  if (last_delivered_chunk_valid && (requested == last_delivered_chunk.chunk_index))
    {
      // pure retry of the chunk we just sent (e.g. the ESP32's CRC check on
      // it failed) - serve straight from the cache, no pipeline/FatFs touch
      send_download_chunk_response (header.sequence_no, last_delivered_chunk);
      return;
    }

  if (requested != download.expected_next_index)
    {
      // only sequential access (plus the exact-retry case above) is
      // supported - see the block comment above download_slot_t
      send_nack (header.sequence_no, WLAN_NACK_OUT_OF_SEQUENCE);
      return;
    }

  unsigned slot = requested % 2;
  if (! download_slot_ready[slot]->wait (pdMS_TO_TICKS (WLAN_LINK_DOWNLOAD_SLOT_TIMEOUT_MS)))
    {
      send_nack (header.sequence_no, WLAN_NACK_INTERNAL_ERROR);
      return;
    }

  if (download_slot[slot].chunk_index != requested)
    {
      // Should not happen given the strict sequential ping-pong contract
      // between this task and download_prefetch_runnable() - a paranoid
      // safety net, not an expected/recoverable path. Surface it as an
      // error instead of sending wrong data; put the (stale) ready token
      // back so a persistent mismatch doesn't also leak a slot's token,
      // and let it NACK repeatedly until the client gives up or the
      // session idle-timeout in wlan_link_handler_runnable() cleans up.
      download_slot_ready[slot]->signal ();
      send_nack (header.sequence_no, WLAN_NACK_INTERNAL_ERROR);
      return;
    }

  last_delivered_chunk = download_slot[slot]; // struct copy, cheap relative to the I/O this overlaps with
  last_delivered_chunk_valid = true;

  send_download_chunk_response (header.sequence_no, last_delivered_chunk);

  download.expected_next_index = requested + 1;
  download_slot_free[slot]->signal (); // let the prefetch task refill this slot
}

static void handle_download_end (const wlan_link_frame_header_t &header)
{
  end_download_session ();
  send_ack (header.sequence_no);
}

static void handle_status_request (const wlan_link_frame_header_t &header)
{
  wlan_link_status_payload_t status;
  status.sd_card_present = wlan_link_sd_card_available () ? 1 : 0;
  status.airborne = is_airborne () ? 1 : 0;
  status.logging_active = logging_active ? 1 : 0;
  status.logging_paused_by_user = logging_paused_by_user ? 1 : 0;

  status.sd_free_bytes = 0;
  status.sd_total_bytes = 0;
  // Skip the fatfs_lock() attempt entirely while logging_active - it holds
  // the lock for the whole logging session (see "Logging pause"), so
  // trying here would just block for the full WLAN_LINK_SD_MUTEX_TIMEOUT_MS
  // and fail anyway; free/total space simply isn't available until logging
  // stops, same as list/download/upload/delete/format.
  if (status.sd_card_present && (! logging_active)
      && fatfs_lock (pdMS_TO_TICKS (WLAN_LINK_SD_MUTEX_TIMEOUT_MS)))
    {
      DWORD free_clusters = 0;
      FATFS *fs = NULL;
      if ((f_getfree ("", &free_clusters, &fs) == FR_OK) && (fs != NULL))
        {
          uint64_t bytes_per_cluster = (uint64_t) fs->csize * fs->ssize;
          status.sd_free_bytes = (uint64_t) free_clusters * bytes_per_cluster;
          status.sd_total_bytes = (uint64_t) (fs->n_fatent - 2) * bytes_per_cluster;
        }
      fatfs_unlock ();
    }
  status.current_sw_version = GIT_TAG_DEC;
  bounded_string_copy (status.stm32_git_tag_info, GIT_TAG_INFO, sizeof(status.stm32_git_tag_info));
  status.gnss_year = coordinates.year;
  status.gnss_month = coordinates.month;
  status.gnss_day = coordinates.day;
  status.gnss_hour = coordinates.hour;
  status.gnss_minute = coordinates.minute;
  status.gnss_second = coordinates.second;

  send_frame (WLAN_FRAME_DATA, header.sequence_no, &status, sizeof(status));
}

//!< Deliberately ungated - unlike every other WLAN command that touches
//!< logging/the SD card, this one must work precisely when logging_active
//!< is stuck true (e.g. flight_mode's GNSS-gated hysteresis never
//!< resolving to ON_GROUND without a settled fix), since that's the
//!< situation it exists to unblock. A user able to reach the sensor's own
//!< WLAN AP to send this is presumed to be physically at the sensor.
//!< logging_paused_by_user auto-clears after LOGGING_PAUSE_TIMEOUT_ITERATIONS
//!< (uSD_handler.cpp) if never explicitly resumed - see "Logging pause".
static void handle_stop_logging_request (const wlan_link_frame_header_t &header)
{
  logging_paused_by_user = true;
  send_ack (header.sequence_no);
}

static void handle_start_logging_request (const wlan_link_frame_header_t &header)
{
  logging_paused_by_user = false;
  logging_force_start = true; // see its doc comment, uSD_handler.cpp
  send_ack (header.sequence_no);
}

static void handle_delete_request (const wlan_link_frame_header_t &header, const uint8_t *payload)
{
  if (logging_active) // Q9: delete shares the update/format logging-active gate
    {
      send_nack (header.sequence_no, WLAN_NACK_LOGGING_ACTIVE);
      return;
    }
  if (! wlan_link_sd_card_available ())
    {
      send_nack (header.sequence_no, WLAN_NACK_NO_SD_CARD);
      return;
    }

  const wlan_link_filename_payload_t *request = (const wlan_link_filename_payload_t*) payload;
  if (! filename_is_safe_relative (request->filename, sizeof(request->filename)))
    {
      send_nack (header.sequence_no, WLAN_NACK_BAD_FILENAME);
      return;
    }

  if (! fatfs_lock (pdMS_TO_TICKS (WLAN_LINK_SD_MUTEX_TIMEOUT_MS)))
    {
      send_nack (header.sequence_no, WLAN_NACK_SD_CARD_BUSY);
      return;
    }

  char path[8 + WLAN_LINK_MAX_FILENAME + 1] = "logger/";
  size_t prefix_len = bounded_strlen (path, sizeof(path));
  size_t name_len = bounded_strlen (request->filename, sizeof(request->filename));
  memcpy (path + prefix_len, request->filename, name_len);
  path[prefix_len + name_len] = 0;

  FRESULT result = f_unlink (path);
  invalidate_list_dir_cache (); // logger/'s contents just changed - see its doc comment
  fatfs_unlock ();

  if (result == FR_NO_FILE)
    {
      send_nack (header.sequence_no, WLAN_NACK_FILE_NOT_FOUND);
      return;
    }
  if (result != FR_OK)
    {
      send_nack (header.sequence_no, WLAN_NACK_INTERNAL_ERROR);
      return;
    }

  send_ack (header.sequence_no);
}

static void handle_format_request (const wlan_link_frame_header_t &header, const uint8_t *payload)
{
  if (logging_active) // Q9: format shares the update/delete logging-active gate
    {
      send_nack (header.sequence_no, WLAN_NACK_LOGGING_ACTIVE);
      return;
    }
  if (! wlan_link_sd_card_available ())
    {
      send_nack (header.sequence_no, WLAN_NACK_NO_SD_CARD);
      return;
    }

  const wlan_link_format_payload_t *request = (const wlan_link_format_payload_t*) payload;
  if (request->confirmation_token != WLAN_LINK_FORMAT_CONFIRMATION_TOKEN)
    {
      send_nack (header.sequence_no, WLAN_NACK_BAD_FORMAT_TOKEN);
      return;
    }

  if (upload.in_progress) // releases its own, separate session lock
    discard_upload ();
  end_download_session (); // releases its own, separate session lock

  if (! fatfs_lock (pdMS_TO_TICKS (WLAN_LINK_SD_MUTEX_TIMEOUT_MS)))
    {
      send_nack (header.sequence_no, WLAN_NACK_SD_CARD_BUSY);
      return;
    }

  invalidate_list_dir_cache (); // about to unmount - can't hold a DIR handle into that
  f_mount (0, "", 0); // unmount before a low-level format

  FRESULT result = f_mkfs ("", FM_ANY, 0, rx_payload_buffer, sizeof(rx_payload_buffer));
  if (result != FR_OK)
    {
      f_mount (&SDFatFS, "", 1); // best-effort: try to get back to a mounted state
      fatfs_unlock ();
      send_nack (header.sequence_no, WLAN_NACK_INTERNAL_ERROR);
      return;
    }

  result = f_mount (&SDFatFS, "", 1);
  if (result == FR_OK)
    {
      sd_card_mounted = true;
      // without a "logger" directory, uSD_handler_runnable() never starts
      // *.lrsx logging at all (uSD_handler.cpp:152-159) - recreate it right
      // away so a freshly formatted card doesn't silently stop logging.
      f_mkdir ("logger");
    }

  fatfs_unlock ();
  send_ack (header.sequence_no);
}

static void dispatch_frame (const wlan_link_frame_header_t &header, uint8_t *payload)
{
  switch (header.frame_type)
    {
    case WLAN_FRAME_UPLOAD_BEGIN:
      handle_upload_begin (header, payload);
      break;
    case WLAN_FRAME_UPLOAD_CHUNK:
      handle_upload_chunk (header, payload);
      break;
    case WLAN_FRAME_UPLOAD_END:
      handle_upload_end (header, payload);
      break;
    case WLAN_FRAME_UPLOAD_ABORT:
      handle_upload_abort (header);
      break;
    case WLAN_FRAME_STATUS_REQUEST:
      handle_status_request (header);
      break;
    case WLAN_FRAME_DELETE_REQUEST:
      handle_delete_request (header, payload);
      break;
    case WLAN_FRAME_FORMAT_REQUEST:
      handle_format_request (header, payload);
      break;
    case WLAN_FRAME_STOP_LOGGING_REQUEST:
      handle_stop_logging_request (header);
      break;
    case WLAN_FRAME_START_LOGGING_REQUEST:
      handle_start_logging_request (header);
      break;
    case WLAN_FRAME_LIST_REQUEST:
      handle_list_request (header, payload);
      break;
    case WLAN_FRAME_DOWNLOAD_BEGIN:
      handle_download_begin (header, payload);
      break;
    case WLAN_FRAME_DOWNLOAD_CHUNK_REQUEST:
      handle_download_chunk_request (header, payload);
      break;
    case WLAN_FRAME_DOWNLOAD_END:
      handle_download_end (header);
      break;
    default:
      send_nack (header.sequence_no, WLAN_NACK_NOT_IMPLEMENTED); // unrecognized frame type
      break;
    }
}

//!< reads WLAN_LINK_CHUNK_SIZE-sized chunks of the active download's file
//!< ahead of demand into the double buffer, overlapping SD reads with the
//!< main task's SPI sends. Owns download.file exclusively - the main task
//!< never touches FatFs directly while a download session is active.
static void download_prefetch_runnable (void*)
{
  for (;;)
    {
      while (! download.active)
	delay (20);

      uint32_t next_prefetch_index = 0;

      while (download.active)
	{
	  unsigned slot = next_prefetch_index % 2;

	  if (! download_slot_free[slot]->wait (pdMS_TO_TICKS (WLAN_LINK_DOWNLOAD_SLOT_TIMEOUT_MS)))
	    continue; // re-check download.active

	  if (! download.active) // session ended while we were waiting for the slot
	    {
	      download_slot_free[slot]->signal (); // hand the token back, harmless once inactive
	      break;
	    }

	  uint32_t offset = next_prefetch_index * WLAN_LINK_CHUNK_SIZE;
	  if (offset >= download.file_size)
	    {
	      download_slot_free[slot]->signal (); // nothing to do yet, don't consume the token
	      delay (50);
	      continue;
	    }

	  FRESULT result = f_lseek (&download.file, offset);
	  UINT bytes_read = 0;
	  if (result == FR_OK)
	    result = f_read (&download.file, download_slot[slot].data, WLAN_LINK_CHUNK_SIZE, &bytes_read);

	  if ((result != FR_OK) || (bytes_read == 0))
	    {
	      download_slot_free[slot]->signal (); // couldn't fill it - leave it "free" rather than wedging the pipeline
	      delay (50);
	      continue;
	    }

	  // hardware CRC unit, not the software wlan_link_crc32_update() loop -
	  // this is the one per-chunk-frequent CRC32 on this link (up to ~100
	  // times/sec at the current SPI clock); see wlan_link_crc32_hw_compute()'s
	  // own doc comment for why it's safe here specifically (single caller)
	  // and documentation/wlan_link.md for the throughput
	  // investigation that led to it.
	  uint32_t crc = wlan_link_crc32_hw_compute (download_slot[slot].data, bytes_read);

	  download_slot[slot].chunk_index = next_prefetch_index;
	  download_slot[slot].valid_bytes = bytes_read;
	  download_slot[slot].crc32 = crc;

	  download_slot_ready[slot]->signal ();
	  ++next_prefetch_index;
	}

      download_prefetch_stopped.signal ();
    }
}

// how long a stalled upload/download session (no relevant frame at all,
// including retries) is tolerated before it's abandoned automatically -
// otherwise a client that vanishes mid-session (e.g. the web page is
// closed, the phone walks out of WiFi range) would leave the fatfs_lock()
// held forever, permanently blocking uSD_handler_task's next flight.
#define WLAN_LINK_SESSION_IDLE_TIMEOUT_MS  30000u
#define WLAN_LINK_SESSION_IDLE_TIMEOUT_HEADER_WAITS \
  ((WLAN_LINK_SESSION_IDLE_TIMEOUT_MS + WLAN_LINK_HEADER_TIMEOUT_MS - 1) / WLAN_LINK_HEADER_TIMEOUT_MS)

//!< this executable owns SPI2 as a slave link to the ESP32
void wlan_link_handler_runnable (void*)
{
  upload.in_progress = false;
  download.active = false;

  // populated here rather than via a static initializer - see the doc
  // comment on the declaration of download_slot_ready/download_slot_free
  download_slot_ready[0] = &download_slot0_ready;
  download_slot_ready[1] = &download_slot1_ready;
  download_slot_free[0]  = &download_slot0_free;
  download_slot_free[1]  = &download_slot1_free;

  configure_wlan_link_gpio_and_spi ();
  register_SPI_usertask (&hspi2);

  unsigned consecutive_header_timeouts = 0;

  for (;;)
    {
      // reference, not a local copy - arm_ready_for_header() below needs a
      // DMA-reachable (non-CCM) target; see rx_header_buffer's declaration
      wlan_link_frame_header_t &header = rx_header_buffer;

      // long idle waits between requests are normal here.
      if (! arm_ready_for_header (&header, WLAN_LINK_HEADER_TIMEOUT_MS))
	{
	  if (upload.in_progress || download.active)
	    {
	      if (++consecutive_header_timeouts >= WLAN_LINK_SESSION_IDLE_TIMEOUT_HEADER_WAITS)
		{
		  discard_upload ();       // no-op if no upload is in progress
		  end_download_session (); // no-op if no download is active
		  consecutive_header_timeouts = 0;
		}
	    }
	  continue;
	}
      consecutive_header_timeouts = 0;

      // Busy from here until the response is sent - see the PA8/IO27
      // handshake in the design doc. Goes high again twice per frame that
      // carries a payload (arm_ready_and_receive(), then
      // arm_ready_and_transmit()), or once for a payload-less request.
      HAL_GPIO_WritePin (WLAN_LINK_READY_GPIO_Port, WLAN_LINK_READY_Pin, GPIO_PIN_RESET);

      uint16_t computed_header_crc = wlan_link_crc16_ccitt ((const uint8_t*) &header, 12);
      if (computed_header_crc != header.header_crc16)
	{
	  // don't trust payload_length from a header that failed its own
	  // check - reply with whatever sequence number we did receive and
	  // go straight back to waiting for the next frame, no payload read.
	  // send_nack() -> send_frame() -> arm_ready_and_transmit() already
	  // raises PA8 again once its response is actually ready to send.
	  send_nack (header.sequence_no, WLAN_NACK_HEADER_CRC);
	  continue;
	}

      bool carries_trailing_crc32 = (header.frame_type == WLAN_FRAME_UPLOAD_CHUNK);
      uint32_t bytes_to_receive = header.payload_length + (carries_trailing_crc32 ? 4u : 0u);

      if (bytes_to_receive > sizeof(rx_payload_buffer))
	{
	  // no response is sent on this path, so PA8 needs to be raised here explicitly
	  HAL_GPIO_WritePin (WLAN_LINK_READY_GPIO_Port, WLAN_LINK_READY_Pin, GPIO_PIN_SET);
	  continue; // can't safely receive this - let the master's transaction time out and retry
	}

      if (bytes_to_receive > 0)
	{
	  // master now waits for PA8 before clocking the payload - see arm_ready_and_receive()'s doc comment.
	  // On false, rx_payload_buffer is undefined/incomplete (arm_ready_and_receive() already recovered the
	  // DMA itself via HAL_SPI_Abort()) - skip dispatch_frame() and go back to waiting for a fresh header,
	  // same as the bytes_to_receive > sizeof(rx_payload_buffer) case just above.
	  if (! arm_ready_and_receive (rx_payload_buffer, (uint16_t) bytes_to_receive))
	    continue;
	}

      // PA8/READY explicitly lowered here, between the payload being
      // received and dispatch_frame() running. Necessary because
      // waitForLinkReady() (ESP32 side) is a plain level poll with no edge
      // detection: without this, the ESP32's next wait (for "response
      // staged", called right after sending the payload) would see the
      // same stale high left over from "payload armed" and return
      // instantly, possibly starting to clock the response before
      // arm_ready_and_transmit() below has actually armed it.
      HAL_GPIO_WritePin (WLAN_LINK_READY_GPIO_Port, WLAN_LINK_READY_Pin, GPIO_PIN_RESET);

      // every dispatch_frame() path ends by sending an ACK/NACK/DATA
      // response, which already raises PA8 again at the right moment.
      dispatch_frame (header, rx_payload_buffer);

      // No delay here, deliberately: PA8/READY stays high continuously
      // from arm_ready_and_transmit() above until arm_ready_for_header()
      // (top of loop) lowers it again - inserting a delay in between would
      // leave READY signaling "ready" while no DMA is actually armed to
      // catch a fast-reacting master's next header.
    }
}

// Both tasks below get a statically pre-aligned stack buffer (the linker's
// "wlan_task_stacks" block, STM32F407VGTX_FLASH.ld) instead of the
// RestrictedTask default of a dynamic, 4KB-aligned allocation out of the
// shared FreeRTOS/CCM heap - that heap didn't reliably have two matching-
// aligned blocks free.

// 2048 words (8KB), matching uSD_handler_task's size - FatFs internals
// (f_lseek/f_read) are stack-hungry; a smaller size MemFault'd on real
// hardware. Doubling the size doubles the required alignment (an MPU
// region's base must be aligned to its own size) - ALIGN(8192) in
// STM32F407VGTX_FLASH.ld matches.
#define WLAN_LINK_STACKSIZE 2048
static StackType_t wlan_link_handler_stack[WLAN_LINK_STACKSIZE]
	__attribute__ ((section ("wlan_task_stacks"), aligned (WLAN_LINK_STACKSIZE * sizeof(StackType_t))));

static TaskParameters_t wlan_link_handler_task_parameters =
{ wlan_link_handler_runnable, "WLAN_LINK", WLAN_LINK_STACKSIZE, 0, WLAN_LINK_PRIORITY,
	wlan_link_handler_stack,
	{
		{ COMMON_BLOCK, COMMON_SIZE, portMPU_REGION_READ_WRITE },
		{ 0, 0, 0 },
		{ 0, 0, 0 }
	}
};
COMMON RestrictedTask wlan_link_handler_task (wlan_link_handler_task_parameters);

// Sized to match WLAN_LINK_STACKSIZE - see its doc comment.
#define WLAN_LINK_DOWNLOAD_PREFETCH_STACKSIZE 2048
static StackType_t wlan_link_download_prefetch_stack[WLAN_LINK_DOWNLOAD_PREFETCH_STACKSIZE]
	__attribute__ ((section ("wlan_task_stacks"), aligned (WLAN_LINK_DOWNLOAD_PREFETCH_STACKSIZE * sizeof(StackType_t))));

static TaskParameters_t wlan_link_download_prefetch_task_parameters =
{ download_prefetch_runnable, "WLAN_DL_PREFETCH", WLAN_LINK_DOWNLOAD_PREFETCH_STACKSIZE, 0, WLAN_LINK_PRIORITY,
	wlan_link_download_prefetch_stack,
	{
		{ COMMON_BLOCK, COMMON_SIZE, portMPU_REGION_READ_WRITE },
		{ 0, 0, 0 },
		{ 0, 0, 0 }
	}
};
COMMON RestrictedTask wlan_link_download_prefetch_task (wlan_link_download_prefetch_task_parameters);
