#!/bin/sh
# Git hook to generate a header file with commit hash and commit time.
echo //generated by post-hook command in .git\hooks > Core/Inc/git-commit-version.h

git log -1 --format='#define GIT_COMMIT_HASH "%h"%n' >> Core/Inc/git-commit-version.h
git show --no-patch --no-notes --pretty='#define GIT_COMMIT_TIME "%cI"%n' >> Core/Inc/git-commit-version.h

echo -n "#define GIT_TAG_INFO \""  >> Core/Inc/git-commit-version.h
git describe --always --dirty --tags > Core/Inc/git-commit-tag.h
echo -e $(cat Core/Inc/git-commit-tag.h)\" >> Core/Inc/git-commit-version.h


