#!/usr/bin/env python3
"""Generate a header with the current git version string as a C define.

Mirrors sw_stm32/scripts/create-git-info-header.py's GIT_TAG_INFO (same
`git describe` invocation, same macro name) so both firmware version
strings share one format. The STM32 side runs its version of this script
from a git post-commit hook; the ESP32 sketch has no equivalent commit
hook mechanism, so this is instead called from build_firmware.py before
compiling. The output is gitignored, and the sketch itself falls back to
a placeholder (see the __has_include guard where GIT_TAG_INFO is used)
when this hasn't been run yet - e.g. a fresh checkout opened directly in
the Arduino IDE instead of built via build_firmware.py.
"""

import subprocess
from pathlib import Path

SCRIPT_DIR = Path(__file__).resolve().parent
OUTPUT_FILE = SCRIPT_DIR.parent / "wlan_link" / "git-commit-version.h"


def main():
    version_string = subprocess.check_output(
        ["git", "describe", "--always", "--dirty", "--tags"], cwd=SCRIPT_DIR
    ).decode("utf-8").strip()

    tag_info_define = f'#define GIT_TAG_INFO "{version_string}"'
    print(tag_info_define)

    with open(OUTPUT_FILE, "w") as f:
        f.write("// generated by create-git-info-header.py - do not edit, do not commit\n")
        f.write(tag_info_define + "\n")


if __name__ == "__main__":
    main()
